title = "HradilBlog"
baseURL = "https://hradilserhii.xyz/Blog"
languageCode = "ru-ru"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "ru"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.ru]
    title = "HradilBlog"
    weight = 1
    contentDir = "content/ru"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "HradilBlog En"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/logo.svg"
  description = "Мой Первый Сайт."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/HradilS"
